const express = require("express");
const { userModel } = require("../Models/User.model");

const userRoute = express.Router();
let results = [
  {
    category: "Sports",
    type: "multiple",
    difficulty: "hard",
    question: "How many times did Martina Navratilova win the Wimbledon Singles Championship?",
    correct_answer: "Nine",
    incorrect_answers: ["Ten", "Seven", "Eight"],
  },
  {
    category: "Sports",
    type: "multiple",
    difficulty: "hard",
    question:
      "Which Italian footballer told Neuer where he&#039;s putting his shot and dragging it wide, during the match Italy-Germany, UEFA EURO 2016?",
    correct_answer: "Pelle",
    incorrect_answers: ["Insigne", "Barzagli", "Giaccherini"],
  },
  {
    category: "Sports",
    type: "multiple",
    difficulty: "hard",
    question:
      "Which female player won the gold medal of table tennis singles in 2016 Olympics Games?",
    correct_answer: "DING Ning (China)",
    incorrect_answers: ["LI Xiaoxia (China)", "Ai FUKUHARA (Japan)", "Song KIM (North Korea)"],
  },
  {
    category: "Sports",
    type: "multiple",
    difficulty: "hard",
    question: "Which player &quot;kung-fu kicked&quot; a Crystal Palace fan in January 1995?",
    correct_answer: "Eric Cantona",
    incorrect_answers: ["David Seamen", "Ashley Cole", "Mark Hughes"],
  },
  {
    category: "Sports",
    type: "multiple",
    difficulty: "hard",
    question: "Who is Manchester United&#039;s leading appearance maker?",
    correct_answer: "Ryan Giggs",
    incorrect_answers: ["David Beckham", "Wayne Rooney", "Eric Cantona"],
  },
  {
    category: "Sports",
    type: "multiple",
    difficulty: "hard",
    question: "What is &ldquo;The Sport of Kings&rdquo;?",
    correct_answer: "Horse Racing",
    incorrect_answers: ["Chess", "Jousting", "Fencing"],
  },
  {
    category: "Sports",
    type: "multiple",
    difficulty: "hard",
    question:
      "Which of these Russian cities did NOT contain a stadium that was used in the 2018 FIFA World Cup?",
    correct_answer: "Vladivostok",
    incorrect_answers: ["Rostov-on-Don", "Yekaterinburg", "Kaliningrad"],
  },
  {
    category: "Sports",
    type: "multiple",
    difficulty: "hard",
    question: "In Canadian football, scoring a rouge is worth how many points?",
    correct_answer: "1",
    incorrect_answers: ["2", "3", "4"],
  },
  {
    category: "Sports",
    type: "multiple",
    difficulty: "hard",
    question: "The AHL affiliate team of the Boston Bruins is named what?",
    correct_answer: "Providence Bruins",
    incorrect_answers: ["New Haven Bruins", "Cambridge Bruins", "Hartford Bruins"],
  },
  {
    category: "Sports",
    type: "multiple",
    difficulty: "hard",
    question: "Which English football team is nicknamed &#039;The Tigers&#039;?",
    correct_answer: "Hull City",
    incorrect_answers: ["Cardiff City", "Bristol City", "Manchester City"],
  },
  {
    category: "Sports",
    type: "multiple",
    difficulty: "medium",
    question:
      "With which team did Michael Schumacher make his Formula One debut at the 1991 Belgian Grand Prix?",
    correct_answer: "Jordan",
    incorrect_answers: ["Benetton", "Ferrari", "Mercedes"],
  },
  {
    category: "Sports",
    type: "multiple",
    difficulty: "medium",
    question: "What cricketing term denotes a batsman being dismissed with a score of zero?",
    correct_answer: "Duck",
    incorrect_answers: ["Bye", "Beamer", "Carry"],
  },
  {
    category: "Sports",
    type: "multiple",
    difficulty: "medium",
    question: "Which Formula One driver was nicknamed &#039;The Professor&#039;?",
    correct_answer: "Alain Prost",
    incorrect_answers: ["Ayrton Senna", "Niki Lauda", "Emerson Fittipaldi"],
  },
  {
    category: "Sports",
    type: "multiple",
    difficulty: "medium",
    question: "Which nation hosted the FIFA World Cup in 2006?",
    correct_answer: "Germany",
    incorrect_answers: ["United Kingdom", "Brazil", "South Africa"],
  },
  {
    category: "Sports",
    type: "multiple",
    difficulty: "medium",
    question: "What is the highest belt you can get in Taekwondo?",
    correct_answer: "Black",
    incorrect_answers: ["White", "Red", "Green"],
  },
  {
    category: "Sports",
    type: "multiple",
    difficulty: "medium",
    question: "Josh Mansour is part of what NRL team?",
    correct_answer: "Penrith Panthers",
    incorrect_answers: ["Melbourne Storm", "Sydney Roosters", "North Queensland Cowboys"],
  },
  {
    category: "Sports",
    type: "multiple",
    difficulty: "medium",
    question: "Which soccer team won the Copa Am&eacute;rica 2015 Championship ?",
    correct_answer: "Chile",
    incorrect_answers: ["Argentina", "Brazil", "Paraguay"],
  },
  {
    category: "Sports",
    type: "multiple",
    difficulty: "medium",
    question:
      "In Formula 1, the Virtual Safety Car was introduced following the fatal crash of which driver?",
    correct_answer: "Jules Bianchi",
    incorrect_answers: ["Ayrton Senna", "Ronald Ratzenberger", "Gilles Villeneuve"],
  },
  {
    category: "Sports",
    type: "multiple",
    difficulty: "medium",
    question: "Who was the topscorer for England national football team?",
    correct_answer: "Wayne Rooney",
    incorrect_answers: ["David Beckham", "Steven Gerrard", "Michael Owen"],
  },
  {
    category: "Sports",
    type: "multiple",
    difficulty: "medium",
    question: "What is the name of the AHL affiliate of the Toronto Maple Leafs?",
    correct_answer: "Toronto Marlies",
    incorrect_answers: ["Toronto Rock", "Toronto Argonauts", "Toronto Wolfpack"],
  },
  {
    category: "Sports",
    type: "multiple",
    difficulty: "easy",
    question: "Which of the following sports is not part of the triathlon?",
    correct_answer: "Horse-Riding",
    incorrect_answers: ["Cycling", "Swimming", "Running"],
  },
  {
    category: "Sports",
    type: "multiple",
    difficulty: "easy",
    question: "In golf, what name is given to a hole score of two under par?",
    correct_answer: "Eagle",
    incorrect_answers: ["Birdie", "Bogey", "Albatross"],
  },
  {
    category: "Sports",
    type: "multiple",
    difficulty: "easy",
    question: "Which driver has been the Formula 1 world champion for a record 7 times?",
    correct_answer: "Michael Schumacher",
    incorrect_answers: ["Ayrton Senna", "Fernando Alonso", "Jim Clark"],
  },
  {
    category: "Sports",
    type: "multiple",
    difficulty: "easy",
    question: "Which team won 2014 FIFA World Cup in Brazil?",
    correct_answer: "Germany",
    incorrect_answers: ["Argentina", "Brazil", "Netherlands"],
  },
  {
    category: "Sports",
    type: "multiple",
    difficulty: "easy",
    question: "Which player holds the NHL record of 2,857 points?",
    correct_answer: "Wayne Gretzky",
    incorrect_answers: ["Mario Lemieux ", "Sidney Crosby", "Gordie Howe"],
  },
  {
    category: "Sports",
    type: "multiple",
    difficulty: "easy",
    question: "What is the name of Manchester United&#039;s home stadium?",
    correct_answer: "Old Trafford",
    incorrect_answers: ["Anfield", "City of Manchester Stadium", "St James Park"],
  },
  {
    category: "Sports",
    type: "multiple",
    difficulty: "easy",
    question: "&quot;Stadium of Light&quot; is the home stadium for which soccer team?",
    correct_answer: "Sunderland FC",
    incorrect_answers: ["Barcelona FC", "Paris Saints-Germain", "Manchester United"],
  },
  {
    category: "Sports",
    type: "multiple",
    difficulty: "easy",
    question: "Which country will host the 2022 FIFA World Cup?",
    correct_answer: "Qatar",
    incorrect_answers: ["USA", "Japan", "Switzerland"],
  },
  {
    category: "Sports",
    type: "multiple",
    difficulty: "easy",
    question: "Who won the UEFA Champions League in 2017?",
    correct_answer: "Real Madrid C.F.",
    incorrect_answers: ["Atletico Madrid", "AS Monaco FC", "Juventus F.C."],
  },
  {
    category: "Sports",
    type: "multiple",
    difficulty: "easy",
    question: "Who won the UEFA Champions League in 2016?",
    correct_answer: "Real Madrid C.F.",
    incorrect_answers: ["FC Bayern Munich", "Atletico Madrid", "Manchester City F.C."],
  },
  {
    category: "Geography",
    type: "multiple",
    difficulty: "easy",
    question: "What colour is the circle on the Japanese flag?",
    correct_answer: "Red",
    incorrect_answers: ["White", "Yellow", "Black"],
  },
  {
    category: "Geography",
    type: "multiple",
    difficulty: "easy",
    question:
      "What is the only state in the United States that does not have a flag in a shape with 4 edges?",
    correct_answer: "Ohio",
    incorrect_answers: ["Florida", "Idaho", "New Mexico"],
  },
  {
    category: "Geography",
    type: "multiple",
    difficulty: "easy",
    question: "What is the 15th letter of the Greek alphabet?",
    correct_answer: "Omicron (&Omicron;)",
    incorrect_answers: ["Sigma (&Sigma;)", "Pi (&Pi;)", "Nu (&Nu;)"],
  },
  {
    category: "Geography",
    type: "multiple",
    difficulty: "easy",
    question: "Which US state has the highest population?",
    correct_answer: "California",
    incorrect_answers: ["New York", "Texas", "Florida"],
  },
  {
    category: "Geography",
    type: "multiple",
    difficulty: "easy",
    question: "What is the official language of Costa Rica?",
    correct_answer: "Spanish",
    incorrect_answers: ["English", "Portuguese", "Creole"],
  },
  {
    category: "Geography",
    type: "multiple",
    difficulty: "easy",
    question: "The Space Needle is located in which city?",
    correct_answer: "Seattle",
    incorrect_answers: ["Los Angles", "Toronto", "Vancouver"],
  },
  {
    category: "Geography",
    type: "multiple",
    difficulty: "easy",
    question: "Harvard University is located in which city?",
    correct_answer: "Cambridge",
    incorrect_answers: ["Providence", "New York", "Washington D.C."],
  },
  {
    category: "Geography",
    type: "multiple",
    difficulty: "easy",
    question: "What is the Polish city known to Germans as Danzig?",
    correct_answer: "Gda\u0144sk",
    incorrect_answers: ["Warsaw", "Zakopane", "Pozna\u0144"],
  },
  {
    category: "Geography",
    type: "multiple",
    difficulty: "easy",
    question: "Where would you find the &quot;Spanish Steps&quot;?",
    correct_answer: "Rome, Italy",
    incorrect_answers: ["Barcelona, Spain", "Berlin, Germany", "London, England"],
  },
  {
    category: "Geography",
    type: "multiple",
    difficulty: "easy",
    question: "What is Laos?",
    correct_answer: "Country",
    incorrect_answers: ["Region", "River", "City"],
  },
  {
    category: "Geography",
    type: "multiple",
    difficulty: "medium",
    question: "Montreal is in which Canadian province?",
    correct_answer: "Quebec",
    incorrect_answers: ["Ontario", "Nova Scotia", "Alberta"],
  },
  {
    category: "Geography",
    type: "multiple",
    difficulty: "medium",
    question: "What is the capital of Peru?",
    correct_answer: "Lima",
    incorrect_answers: ["Santiago", "Montevideo", "Buenos Aires"],
  },
  {
    category: "Geography",
    type: "multiple",
    difficulty: "medium",
    question:
      "What is the name of the former country that was succeeded by countries such as Serbia, Croatia and Slovenia?",
    correct_answer: "Yugoslavia",
    incorrect_answers: ["Czechoslovakia", "Abkhazia", "South Ossetia"],
  },
  {
    category: "Geography",
    type: "multiple",
    difficulty: "medium",
    question: "What is the capital of Chile?",
    correct_answer: "Santiago",
    incorrect_answers: ["Valpara&iacute;so", "Copiap&oacute;", "Antofagasta"],
  },
  {
    category: "Geography",
    type: "multiple",
    difficulty: "medium",
    question: "What African country has Portuguese as its official language?",
    correct_answer: "Mozambique",
    incorrect_answers: ["Botswana", "Gabon", "Togo"],
  },
  {
    category: "Geography",
    type: "multiple",
    difficulty: "medium",
    question: "Broome is a town in which state of Australia?",
    correct_answer: "Western Australia",
    incorrect_answers: ["Northern Territory", "South Australia", "Tasmania"],
  },
  {
    category: "Geography",
    type: "multiple",
    difficulty: "medium",
    question: "How many states are in Australia?",
    correct_answer: "6",
    incorrect_answers: ["7", "8", "5"],
  },
  {
    category: "Geography",
    type: "multiple",
    difficulty: "hard",
    question: "Which of these cities is NOT in England?",
    correct_answer: "Edinburgh",
    incorrect_answers: ["Oxford", "Manchester", "Southampton"],
  },
  {
    category: "Geography",
    type: "multiple",
    difficulty: "hard",
    question: "Which country is the Taedong River in?",
    correct_answer: "North Korea",
    incorrect_answers: ["South Korea", "Japan", "China"],
  },
  {
    category: "Geography",
    type: "multiple",
    difficulty: "medium",
    question: "Where is Hadrian&#039;s Wall located?",
    correct_answer: "Carlisle, England",
    incorrect_answers: ["Rome, Italy", "Alexandria, Egypt", "Dublin, Ireland"],
  },
  {
    category: "Entertainment: Film",
    type: "multiple",
    difficulty: "easy",
    question: "Which of the following was not one of &quot;The Magnificent Seven&quot;?",
    correct_answer: "Clint Eastwood",
    incorrect_answers: ["Steve McQueen", "Charles Bronson", "Robert Vaughn"],
  },
  {
    category: "Entertainment: Film",
    type: "multiple",
    difficulty: "easy",
    question: "Which of the following movies was not based on a novel by Stephen King? ",
    correct_answer: "The Thing",
    incorrect_answers: ["Carrie", "Misery", "The Green Mile"],
  },
  {
    category: "Entertainment: Film",
    type: "multiple",
    difficulty: "easy",
    question: "Who directed &quot;E.T. the Extra-Terrestrial&quot; (1982)?",
    correct_answer: "Steven Spielberg",
    incorrect_answers: ["Stanley Kubrick", "James Cameron", "Tim Burton"],
  },
  {
    category: "Entertainment: Film",
    type: "multiple",
    difficulty: "easy",
    question: "Who wrote and directed the 1986 film &#039;Platoon&#039;?",
    correct_answer: "Oliver Stone",
    incorrect_answers: ["Francis Ford Coppola", "Stanley Kubrick", "Michael Cimino"],
  },
  {
    category: "Entertainment: Film",
    type: "multiple",
    difficulty: "easy",
    question: "Who starred in the film 1973 movie &quot;Enter The Dragon&quot;?",
    correct_answer: "Bruce Lee",
    incorrect_answers: ["Jackie Chan", "Jet Li", " Yun-Fat Chow"],
  },
  {
    category: "Entertainment: Film",
    type: "multiple",
    difficulty: "easy",
    question: "Who directed the 2015 movie &quot;The Revenant&quot;?",
    correct_answer: "Alejandro G. I&ntilde;&aacute;rritu",
    incorrect_answers: ["Christopher Nolan", "David Fincher", "Wes Anderson"],
  },
  {
    category: "Entertainment: Film",
    type: "multiple",
    difficulty: "easy",
    question:
      "What is the orange and white bot&#039;s name in &quot;Star Wars: The Force Awakens&quot;?",
    correct_answer: "BB-8",
    incorrect_answers: ["BB-3", "AA-A", "R2-D2"],
  },
  {
    category: "Entertainment: Film",
    type: "multiple",
    difficulty: "easy",
    question:
      "In the 1992 film &quot;Army of Darkness&quot;, what name does Ash give to his double-barreled shotgun?",
    correct_answer: "Boomstick",
    incorrect_answers: ["Bloomstick", "Blastbranch", "2-Pump Chump"],
  },
  {
    category: "Entertainment: Film",
    type: "multiple",
    difficulty: "easy",
    question:
      "What is the name of the fictional retro-mod band starring Austin Powers as the lead vocalist?",
    correct_answer: "Ming Tea",
    incorrect_answers: ["Cough Fi", "Spear Mint", "Mister E"],
  },
  {
    category: "Entertainment: Film",
    type: "multiple",
    difficulty: "easy",
    question: "In &quot;ALF&quot;, what was ALF&#039;s real name?",
    correct_answer: "Gordon Shumway",
    incorrect_answers: ["Gordon Milipp", "Gordon Foster", "Gordon von Gam"],
  },
  {
    category: "Mythology",
    type: "multiple",
    difficulty: "easy",
    question: "The ancient Roman god of war was commonly known as which of the following?",
    correct_answer: "Mars",
    incorrect_answers: ["Jupiter", "Juno", "Ares"],
  },
  {
    category: "Mythology",
    type: "multiple",
    difficulty: "easy",
    question:
      "This Greek goddess&#039;s name was chosen for the dwarf planet responsible for discord on Pluto&#039;s classification amongst astronomers.",
    correct_answer: "Eris",
    incorrect_answers: ["Charon", "Ceres", "Dysnomia"],
  },
  {
    category: "Mythology",
    type: "multiple",
    difficulty: "easy",
    question: "Who was the King of Gods in Ancient Greek mythology?",
    correct_answer: "Zeus",
    incorrect_answers: ["Apollo", "Hermes", "Poseidon"],
  },
  {
    category: "Mythology",
    type: "multiple",
    difficulty: "easy",
    question:
      "Which Greek &amp; Roman god was known as the god of music, truth and prophecy, healing, the sun and light, plague, poetry, and more?",
    correct_answer: "Apollo",
    incorrect_answers: ["Aphrodite", "Artemis", "Athena"],
  },
  {
    category: "Mythology",
    type: "multiple",
    difficulty: "easy",
    question: "The greek god Poseidon was the god of what?",
    correct_answer: "The Sea",
    incorrect_answers: ["War", "Sun", "Fire"],
  },
  {
    category: "Mythology",
    type: "multiple",
    difficulty: "easy",
    question:
      "Which figure from Greek mythology traveled to the underworld to return his wife Eurydice to the land of the living?",
    correct_answer: "Orpheus",
    incorrect_answers: ["Hercules", "Perseus", "Daedalus"],
  },
  {
    category: "Mythology",
    type: "multiple",
    difficulty: "easy",
    question: "In Greek mythology, who is the god of wine?",
    correct_answer: "Dionysus",
    incorrect_answers: ["Hephaestus", "Demeter", "Apollo"],
  },
  {
    category: "Mythology",
    type: "multiple",
    difficulty: "easy",
    question: "Which of these mythological creatures is said to be half-man and half-horse?",
    correct_answer: "Centaur",
    incorrect_answers: ["Minotaur", "Pegasus", "Gorgon"],
  },
  {
    category: "Mythology",
    type: "multiple",
    difficulty: "easy",
    question: "What mythology did the god &quot;Apollo&quot; come from?",
    correct_answer: "Greek and Roman",
    incorrect_answers: ["Roman and Spanish", "Greek and Chinese", "Greek, Roman and Norse"],
  },
  {
    category: "Mythology",
    type: "multiple",
    difficulty: "easy",
    question: "What mytological creatures have women&#039;s faces and vultures&#039; bodies?",
    correct_answer: "Harpies",
    incorrect_answers: ["Mermaids", "Nymph", "Lilith"],
  },
  {
    category: "Mythology",
    type: "multiple",
    difficulty: "medium",
    question: "Who was the Roman god of fire?",
    correct_answer: "Vulcan",
    incorrect_answers: ["Apollo", "Jupiter", "Mercury"],
  },
  {
    category: "Mythology",
    type: "multiple",
    difficulty: "medium",
    question: "Neptune&#039;s greek name was...",
    correct_answer: "Poseidon",
    incorrect_answers: ["Ares", "Zeus", "Apollo"],
  },
  {
    category: "Mythology",
    type: "multiple",
    difficulty: "medium",
    question: "Which of the following Mesopotamian mythological figures was NOT a deity?",
    correct_answer: "Enkidu",
    incorrect_answers: ["Enki", "Enlil", "Enkimdu"],
  },
  {
    category: "Mythology",
    type: "multiple",
    difficulty: "medium",
    question: "Which of these Roman gods doesn&#039;t have a counterpart in Greek mythology?",
    correct_answer: "Janus",
    incorrect_answers: ["Vulcan", "Juno", "Mars"],
  },
  {
    category: "Mythology",
    type: "multiple",
    difficulty: "medium",
    question: "What is the name of the Greek god of blacksmiths?",
    correct_answer: "Hephaestus",
    incorrect_answers: ["Dyntos", "Vulcan", "Artagatus"],
  },
  {
    category: "Mythology",
    type: "multiple",
    difficulty: "medium",
    question:
      "In African mythology, Anansi is a trickster and storyteller who takes the shape of which animal?",
    correct_answer: "Spider",
    incorrect_answers: ["Wild dog", "Monkey", "Crocodile"],
  },
  {
    category: "Mythology",
    type: "multiple",
    difficulty: "medium",
    question: "According to Japanese folklore, what is the favorite food of the Kappa.",
    correct_answer: "Cucumbers",
    incorrect_answers: ["Kabocha", "Nasu", "Soba"],
  },
  {
    category: "Mythology",
    type: "multiple",
    difficulty: "medium",
    question:
      "The Norse god Odin has two pet crows named &quot;Huginn&quot; and &quot;Muninn&quot;.  What do their names mean?",
    correct_answer: "Thought &amp; Memory",
    incorrect_answers: ["Power &amp; Peace", "War &amp; Learning", "Sleeping &amp; Waking"],
  },
  {
    category: "Mythology",
    type: "multiple",
    difficulty: "medium",
    question: "What is the name of the first human being in Norse mythology?",
    correct_answer: "Ask",
    incorrect_answers: ["Asmund", "Ake", "Asger"],
  },
  {
    category: "Mythology",
    type: "multiple",
    difficulty: "medium",
    question:
      "What animal did Queen Pasipahe sleep with before she gave birth to the Minotaur in Greek Mythology?",
    correct_answer: "Bull",
    incorrect_answers: ["Pig", "Ox", "Horse"],
  },
  {
    category: "Mythology",
    type: "multiple",
    difficulty: "hard",
    question: "Talos, the mythical giant bronze man, was the protector of which island?",
    correct_answer: "Crete",
    incorrect_answers: ["Sardinia", "Sicily", "Cyprus"],
  },
  {
    category: "Mythology",
    type: "multiple",
    difficulty: "hard",
    question: "What was the punishment for Sysiphus&#039;s craftiness?",
    correct_answer: "Cursed to roll a boulder up a hill for eternity.",
    incorrect_answers: [
      "Tied to a boulder for eternity, being pecked by birds.",
      "Standing in a lake filled with water he could not drink.",
      "To fell a tree that regenerated after every axe swing.",
    ],
  },
  {
    category: "Mythology",
    type: "multiple",
    difficulty: "hard",
    question: "According to Algonquian folklore, how does one transform into a Wendigo?",
    correct_answer: "Participating in cannibalism.",
    incorrect_answers: [
      "Excessive mutilation of animal corpses.",
      "Performing a ritual involving murder.",
      "Drinking the blood of many slain animals.",
    ],
  },
  {
    category: "Mythology",
    type: "multiple",
    difficulty: "hard",
    question:
      "In Norse mythology, what is the name of the serpent which eats the roots of the ash tree Yggdrasil?",
    correct_answer: "Nidhogg",
    incorrect_answers: ["Bragi", "Odin", "Ymir"],
  },
  {
    category: "Mythology",
    type: "multiple",
    difficulty: "hard",
    question: "Which of the following is NOT a god in Norse Mythology.",
    correct_answer: "Jens",
    incorrect_answers: ["Loki", "Tyr", "Snotra"],
  },
  {
    category: "Mythology",
    type: "multiple",
    difficulty: "hard",
    question: "Nidhogg is a mythical creature from what mythology?",
    correct_answer: "Norse",
    incorrect_answers: ["Egyptian", "Greek", "Hindu"],
  },
  {
    category: "Mythology",
    type: "multiple",
    difficulty: "hard",
    question: "Who is the Egyptian god of reproduction and lettuce?",
    correct_answer: "Min",
    incorrect_answers: ["Menu", "Mut", "Meret"],
  },
  {
    category: "Mythology",
    type: "multiple",
    difficulty: "hard",
    question: "What immense structure is referred to in Norse Mythology as the Yggdrasil.",
    correct_answer: "Tree",
    incorrect_answers: ["Mountain", "Temple", "Castle"],
  },
  {
    category: "Mythology",
    type: "multiple",
    difficulty: "hard",
    question: "Which Norse God has a horse named Sleipnir?",
    correct_answer: "Odin",
    incorrect_answers: ["Thor", "Frigg", "Balder"],
  },
  {
    category: "Mythology",
    type: "multiple",
    difficulty: "hard",
    question:
      "Who is a minor god that is protector and creator of various arts, such as cheese making and bee keeping.",
    correct_answer: "Aristaeus",
    incorrect_answers: ["Autonoe", "Carme", "Cephisso"],
  },
];

userRoute.post("/quiz", async (req, res) => {
  let { name, category, difficulty, questions } = req.body;
  results.filter((item) => {
    return item.category === category;
  });
  results.filter((item) => {
    return (item.difficulty = difficulty);
  });
  let final = results.slice(0, questions);
  res.send({ results: final });
});

userRoute.post("/savescore", async (req, res) => {
  let { name, score } = req.body;
  console.log(name,score,"see");
  try {
    let newuser = new userModel({ name, score })
    await newuser.save()
  } catch (error) {
    console.log(error)
  }
})

userRoute.get("/getscore", async (req, res) => {
  try {
    let users = await userModel.find();
    console.log(users);
    res.send({ users: users });
  } catch (error) {
    console.log(error.message);
  }
});

module.exports = { userRoute };
